apiVersion: apps.3scale.net/v1alpha1
kind: APIcast
metadata:
  name: apicast-production-movel
  namespace: redes-3scale-apicast
spec:
  adminPortalCredentialsRef:
    name: apicast-configuration-url-secret
  enabledServices:
    - '61'
    - '62'
    - '63'
    - '67'
    - '79'
    - '80'
    - '87'
    - '90'
  extendedMetrics: true
  logLevel: info
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  responseCodesIncluded: true
  timezone: America/Sao_Paulo
